version: '3.8'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27018:27017"
  express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
